var Workers;
(function(Workers1) {
    Workers1["SERVICE_DEV_READY"] = 'SERVICE_DEV_READY';
    Workers1["INIT_MESSAGE_SERVICE_DEV"] = 'INIT_MESSAGE_SERVICE_DEV';
    Workers1["SERVICE_DEV_GET_PORT"] = 'SERVICE_DEV_GET_PORT';
    Workers1["LSP_SEND_PORT"] = 'LSP_SEND_PORT';
    Workers1["LSP_OPEN_WEBVIEW"] = 'LSP_OPEN_WEBVIEW';
    Workers1["LSP_UPDATE_CURRENT_COMPONENT"] = 'LSP_UPDATE_CURRENT_COMPONENT';
    Workers1["LSP_UPDATE_SERVER_COMPONENT"] = 'LSP_UPDATE_SERVER_COMPONENT';
    Workers1["LSP_CURRENT_COMPONENT_RENDERED"] = 'LSP_CURRENT_COMPONENT_RENDERED';
    Workers1["LSP_SEND_COMPONENT_INFORMATIONS"] = 'LSP_SEND_COMPONENT_INFORMATIONS';
    Workers1["LSP_SEND_ROOT_COMPONENT_FILE"] = 'LSP_SEND_ROOT_COMPONENT_FILE';
    Workers1["LSP_ERROR"] = 'LSP_ERROR';
    Workers1["LSP_CLOSE"] = 'LSP_CLOSE';
    Workers1["LSP_WS_PORT_FILE"] = 'OWS_PORT';
})(Workers || (Workers = {
}));
export default Workers;
